In [1]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [2]:
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.telkom.tracencare',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=100000,
    filter_score_with=None
)

In [3]:
df_pl = pd.DataFrame(np.array(result),columns=['review'])

df_pl = df_pl.join(pd.DataFrame(df_pl.pop('review').tolist()))

df_pl.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,7f287882-24d4-4b47-ba99-ed9c6233b2ab,IAM CHANNEL,https://play-lh.googleusercontent.com/a-/AOh14...,Tolong dong perbaiki apk nya. Mau rubah data t...,3,115,4.4.6,2022-06-20 12:49:30,"Halo Kakak,\n\nMohon maaf atas ketidaknyamanan...",2022-06-20 13:29:08
1,1869c3ca-62f7-413e-b60c-367313ce3955,daz bones,https://play-lh.googleusercontent.com/a-/AOh14...,"aplikasi sering trouble dan tambahan, petugas ...",1,346,4.4.6,2022-06-16 21:27:41,"Halo Kak,\n\nSebelumnya kami mohon maaf atas k...",2022-06-17 10:10:49
2,e628791d-1915-4596-9167-745747dafb4c,Ni Wayan Lisa Vania,https://play-lh.googleusercontent.com/a/AATXAJ...,Opsi permintaan aplikasi bertele-tele. Saya su...,4,1168,4.4.5,2022-06-10 11:34:48,"Halo Ni Wayan Lisa Vania,\n\nKami mohon maaf a...",2022-06-10 12:35:49
3,f6cba08e-d4b7-4ef7-9ec2-c89b14c122c3,ande-ande lumut,https://play-lh.googleusercontent.com/a-/AOh14...,"Tolong dooong aplikasinya diperbaiki, kelihata...",1,159,4.4.6,2022-06-18 09:06:30,"Halo Kakak,\n\nMohon maaf atas ketidaknyamanan...",2022-06-18 12:13:22
4,22177863-7d06-417b-ad30-8be8fd1bb72b,Refsimardiani Safitri,https://play-lh.googleusercontent.com/a/AATXAJ...,Awal2 dlu sangat membantu. Tidak seperti saat ...,2,787,4.4.5,2022-06-10 14:54:45,"Halo,\n\nSebagai alternatif, Anda dapat melaku...",2022-06-10 17:09:25

In [4]:
len(df_pl.index)

100000

In [5]:
df_pl[['userName', 'score','at', 'content']].head()

,userName,score,at,content
0,IAM CHANNEL,3,2022-06-20 12:49:30,Tolong dong perbaiki apk nya. Mau rubah data t...
1,daz bones,1,2022-06-16 21:27:41,"aplikasi sering trouble dan tambahan, petugas ..."
2,Ni Wayan Lisa Vania,4,2022-06-10 11:34:48,Opsi permintaan aplikasi bertele-tele. Saya su...
3,ande-ande lumut,1,2022-06-18 09:06:30,"Tolong dooong aplikasinya diperbaiki, kelihata..."
4,Refsimardiani Safitri,2,2022-06-10 14:54:45,Awal2 dlu sangat membantu. Tidak seperti saat ...

In [6]:
new_df = df_pl[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False)
sorted_df.head()

,userName,score,at,content
68446,Purwanto,5,2022-06-22 18:01:46,Mohon infonya dong agar vaksin LN bisa masuk k...
93528,Abi Atturhaq,1,2022-06-22 17:01:25,"Di update malah g bisa buka sertifikat vaksin,..."
37710,Fuad Baedlowi,5,2022-06-22 16:58:03,Terimakasih PeduliLindungi
1431,Indo show,1,2022-06-22 10:18:49,Update Yg Baru Malah Ribet ...Mau Daftar Pelay...
4419,SURYA 2112,1,2022-06-22 09:19:01,"Aplikasi payah , mainin data masyarakat , udah..."

In [7]:
my_df = sorted_df[['userName', 'score','at', 'content']]

In [8]:
my_df.head()

,userName,score,at,content
68446,Purwanto,5,2022-06-22 18:01:46,Mohon infonya dong agar vaksin LN bisa masuk k...
93528,Abi Atturhaq,1,2022-06-22 17:01:25,"Di update malah g bisa buka sertifikat vaksin,..."
37710,Fuad Baedlowi,5,2022-06-22 16:58:03,Terimakasih PeduliLindungi
1431,Indo show,1,2022-06-22 10:18:49,Update Yg Baru Malah Ribet ...Mau Daftar Pelay...
4419,SURYA 2112,1,2022-06-22 09:19:01,"Aplikasi payah , mainin data masyarakat , udah..."

In [9]:
my_df.to_csv("scrapped_data.csv", index = False)

Error: need to escape, but no escapechar set